import './globals.css'
import type { Metadata } from 'next'
import { PHProvider, PostHogPageview } from './providers';
import { ReactNode, Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="en">
      <Suspense>
        <PostHogPageview />
      </Suspense>
      <PHProvider>
        <body className="relative w-screen h-full min-h-screen ">
          {children}
        </body>
      </PHProvider>
    </html>
  )
}
